# Generated by Django 5.2.5 on 2025-09-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmmoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ArmedConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['started_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('born_at', models.DateField()),
                ('died_at', models.DateField(default=None, null=True)),
            ],
            options={
                'ordering': ['name', 'born_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('participated_in_conflicts', models.ManyToManyField(to='rifles.armedconflict')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
                ('ammo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifles.ammotype')),
                ('constructors', models.ManyToManyField(to='rifles.constructor')),
                ('country_of_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rifles.country')),
                ('used_in_conflicts', models.ManyToManyField(to='rifles.armedconflict')),
            ],
            options={
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
