# Generated by Django 5.2.5 on 2025-09-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammotype',
            options={'ordering': ['title'], 'verbose_name': 'Калибр', 'verbose_name_plural': 'Калибры'},
        ),
        migrations.AlterModelOptions(
            name='armedconflict',
            options={'ordering': ['started_at', 'title'], 'verbose_name': 'Вооруженный конфликт', 'verbose_name_plural': 'Вооруженные конфликты'},
        ),
        migrations.AlterModelOptions(
            name='constructor',
            options={'ordering': ['name', 'born_at'], 'verbose_name': 'Конструктор', 'verbose_name_plural': 'Конструкторы'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='rifle',
            options={'ordering': ['title', 'created_at'], 'verbose_name': 'Винтовка', 'verbose_name_plural': 'Винтовки'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='participated_in_conflicts',
        ),
        migrations.AddField(
            model_name='armedconflict',
            name='countries',
            field=models.ManyToManyField(to='rifles.country', verbose_name='Страны-участники'),
        ),
        migrations.AlterField(
            model_name='ammotype',
            name='created_at',
            field=models.DateField(verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='ammotype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ammotype',
            name='title',
            field=models.TextField(verbose_name='Название калибра'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='started_at',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='title',
            field=models.TextField(verbose_name='Название конфликта'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='born_at',
            field=models.DateField(verbose_name='Родился'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='died_at',
            field=models.DateField(default=None, null=True, verbose_name='Умер'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='name',
            field=models.TextField(verbose_name='Имя конструктора'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='ammo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifles.ammotype', verbose_name='Тип патрон'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='constructors',
            field=models.ManyToManyField(to='rifles.constructor', verbose_name='Создатели'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='country_of_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rifles.country', verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='created_at',
            field=models.DateField(verbose_name='Создана в'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='title',
            field=models.TextField(verbose_name='Название винтовки'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='used_in_conflicts',
            field=models.ManyToManyField(to='rifles.armedconflict', verbose_name='Была использована в конфликтах'),
        ),
    ]
