# Generated by Django 5.2.5 on 2025-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0002_alter_ammotype_options_alter_armedconflict_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armedconflict',
            name='finished_at',
            field=models.DateField(null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='started_at',
            field=models.DateField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='used_in_conflicts',
            field=models.ManyToManyField(null=True, to='rifles.armedconflict', verbose_name='Была использована в конфликтах'),
        ),
    ]
