# Generated by Django 5.2.5 on 2025-09-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0003_alter_armedconflict_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armedconflict',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='died_at',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Умер'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='used_in_conflicts',
            field=models.ManyToManyField(blank=True, to='rifles.armedconflict', verbose_name='Была использована в конфликтах'),
        ),
    ]
