# Generated by Django 5.2.5 on 2025-09-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0004_alter_armedconflict_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammotype',
            options={'verbose_name': 'Калибр', 'verbose_name_plural': 'Калибры'},
        ),
        migrations.AlterModelOptions(
            name='armedconflict',
            options={'verbose_name': 'Вооруженный конфликт', 'verbose_name_plural': 'Вооруженные конфликты'},
        ),
        migrations.AlterModelOptions(
            name='constructor',
            options={'verbose_name': 'Конструктор', 'verbose_name_plural': 'Конструкторы'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='rifle',
            options={'verbose_name': 'Винтовка', 'verbose_name_plural': 'Винтовки'},
        ),
        migrations.AlterField(
            model_name='ammotype',
            name='created_at',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='started_at',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='born_at',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='died_at',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='created_at',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
