# Generated by Django 5.2.5 on 2025-09-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0005_alter_ammotype_options_alter_armedconflict_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammotype',
            name='created_at',
            field=models.DateField(blank=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ammotype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ammotype',
            name='title',
            field=models.TextField(blank=True, verbose_name='Название калибра'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='countries',
            field=models.ManyToManyField(blank=True, to='rifles.country', verbose_name='Страны-участники'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='started_at',
            field=models.DateField(blank=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='armedconflict',
            name='title',
            field=models.TextField(blank=True, verbose_name='Название конфликта'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='born_at',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='name',
            field=models.TextField(blank=True, verbose_name='Имя конструктора'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(blank=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='ammo_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rifles.ammotype', verbose_name='Тип патрон'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='constructors',
            field=models.ManyToManyField(blank=True, to='rifles.constructor', verbose_name='Создатели'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rifles.country', verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='created_at',
            field=models.DateField(blank=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='title',
            field=models.TextField(blank=True, verbose_name='Название винтовки'),
        ),
    ]
