# Generated by Django 5.2.5 on 2026-07-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0007_alter_ammotype_created_at_alter_ammotype_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ammotype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ammotype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='armedconflict',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='constructor',
            name='description',
        ),
    ]
