# Generated by Django 5.2.5 on 2026-07-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0008_remove_ammotype_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifle',
            name='country_of_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifles.country', verbose_name='Страна происхождения'),
        ),
    ]
