# Generated by Django 5.2.5 on 2026-08-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20260815_1927'),
        ('rifles', '0009_alter_rifle_country_of_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Обвес')),
            ],
            options={
                'verbose_name': 'Обвес',
                'verbose_name_plural': 'Обвесы',
            },
        ),
        migrations.CreateModel(
            name='TypeOfMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Тип крепления')),
            ],
            options={
                'verbose_name': 'Тип крепления',
                'verbose_name_plural': 'Типы крепления',
            },
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название сборки')),
                ('attachments', models.ManyToManyField(blank=True, to='rifles.attachment', verbose_name='Обвесы')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.userprofile', verbose_name='Создатель сборки')),
                ('rifle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifles.rifle', verbose_name='Винтовка')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='type_of_mount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifles.typeofmount', verbose_name='Тип крепления'),
        ),
        migrations.AddField(
            model_name='rifle',
            name='types_of_mounts',
            field=models.ManyToManyField(blank=True, to='rifles.typeofmount', verbose_name='Типы креплений'),
        ),
    ]
