# Generated by Django 5.2.5 on 2026-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0010_attachment_typeofmount_loadout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='rifles', verbose_name='Изображение'),
        ),
    ]
