# Generated by Django 5.2.5 on 2026-09-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0011_rifle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofmount',
            name='title',
            field=models.TextField(unique=True, verbose_name='Тип крепления'),
        ),
    ]
