# Generated by Django 5.2.5 on 2026-09-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0012_alter_typeofmount_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadoutAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifles.loadout')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rifles.attachment')),
            ],
            options={
                'verbose_name': 'Обвес в сборке',
                'verbose_name_plural': 'Обвесы в сборке',
                'unique_together': {('loadout', 'attachment')},
            },
        ),
    ]