# Generated by Django 5.2.5 on 2026-09-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0013_create_loadoutattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadout',
            name='attachments',
        ),
    ]