# Generated by Django 5.2.5 on 2026-09-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0014_remove_loadout_attachments'),
        ('rifles', '0013_create_loadoutattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadout',
            name='attachments',
            field=models.ManyToManyField(blank=True, through='LoadoutAttachment', to='rifles.attachment', verbose_name='Обвесы'),
        ),
    ]