# Generated by Django 5.2.5 on 2026-09-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifles', '0015_add_loadout_attachments_with_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='loadout',
            name='attachments',
            field=models.ManyToManyField(blank=True, through='rifles.LoadoutAttachment', to='rifles.attachment', verbose_name='Обвесы'),
        ),
    ]
