# Generated by Django 5.2.5 on 2026-08-15 11:27

from django.db import migrations
from django.contrib.auth.models import User

from general.models import UserProfile

def create_userprofiles_for_old_users(apps, schema_editor):
    users = User.objects.all()
    for user in users:
        try:
            user.userprofile
        except UserProfile.DoesNotExist:
            UserProfile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_userprofiles_for_old_users)
    ]
