# Generated by Django 5.2.5 on 2026-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20260815_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.TextField(choices=[('moderator', 'модератор'), ('builder', 'сборщик')], null=True),
        ),
    ]
