# Generated by Django 5.2.5 on 2026-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.TextField(choices=[('moderator', 'модератор'), ('builder', 'сборщик'), ('reader', 'читатель')], null=True),
        ),
    ]
