# Generated by Django 5.2.5 on 2026-08-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create_loadouts', 'Может создавать сборки')]},
        ),
    ]
