# Generated by Django 5.2.5 on 2026-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.TextField(choices=[('moderator', 'модератор'), ('builder', 'сборщик'), ('reader', 'читатель')]),
        ),
    ]
