# Generated by Django 5.2.5 on 2026-08-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_userprofile_options_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Расширение пользователя', 'verbose_name_plural': 'Расширения пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.TextField(choices=[('moderator', 'модератор'), ('builder', 'сборщик'), ('reader', 'читатель')], verbose_name='Тип пользователя'),
        ),
    ]
