# Generated by Django 5.2.5 on 2026-08-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_userprofile_options_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.TextField(choices=[('moderator', 'модератор'), ('builder', 'сборщик'), ('reader', 'читатель')], default='reader', verbose_name='Тип пользователя'),
        ),
    ]
