# Generated by Django 5.2.5 on 2026-09-01 13:15
import pyotp
from django.db import migrations, models

def fill_totp_field(apps, schema_editor):
    UserProfile = apps.get_model("general", "UserProfile")
    for u in UserProfile.objects.all():
        u.totp_key = pyotp.random_hex()
        u.save()

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_userprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(fill_totp_field)
    ]
