# Generated by Django 5.2.5 on 2026-09-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_userprofile_totp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
